-- Create mock folders
INSERT INTO noteful_folders (folder_name)
  VALUES
  ('Important'),
  ('Super'),
  ('Spangley');

-- Create mock notes
INSERT INTO noteful_notes (note_name, date_created, folder_id, note_content)
  VALUES
  ('Dogs', '2019-01-03T00:00:00.000Z', 2,
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed iaculis ante fermentum est cursus, ut hendrerit dui pellentesque. Proin a est eget leo finibus blandit. Praesent eu gravida ante. Cras sit amet sagittis ex. Cras consectetur, sem efficitur tempus dignissim, odio magna lobortis magna, a finibus sem nisl eget mauris. Aenean sapien ipsum, blandit et nisi vehicula, gravida pharetra sapien. Mauris nec varius est, vitae venenatis lectus. Vestibulum scelerisque augue et ante tempus, vehicula imperdiet purus accumsan. Proin in volutpat nulla, quis tincidunt massa. Praesent efficitur risus in elit varius blandit. Praesent non mollis tellus, at dignissim est. Praesent nec lacus tristique, venenatis tortor quis, fringilla felis. Cras rhoncus, diam non elementum condimentum, nunc tellus fermentum enim, eget dapibus nunc sapien et ante. Nulla ut felis a arcu maximus condimentum sit amet eu eros. Curabitur vel viverra turpis, at ullamcorper diam.'),
  ('Cats', '2018-08-15T23:00:00.000Z', 2,
  'Phasellus dictum eget metus at fringilla. Aenean a suscipit augue. Fusce in viverra nulla. Nam luctus sollicitudin eros, at consectetur augue. Nam sed nisl tellus. Integer nec lacus egestas, luctus quam ut, feugiat mauris. Duis id dui quis nulla volutpat tincidunt.'),
  ('Pigs', '2018-03-01T00:00:00.000Z', 3,
  'Sed venenatis quis metus id pretium. Donec dignissim mollis eros, eu luctus lorem ultricies sit amet. Nullam porta, nisi sit amet ullamcorper sollicitudin, augue diam bibendum erat, non varius ipsum elit non quam. Sed nisi neque, euismod in condimentum at, tempor in ex. Ut lobortis, odio quis interdum luctus, metus sapien lobortis neque, et vulputate risus nisl et ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent non quam scelerisque, congue urna ac, viverra sem. Nulla facilisi. Donec tempus, orci eu ornare ornare, mi neque vulputate lorem, eget finibus tortor justo vitae ipsum. Maecenas a leo pharetra, vestibulum sem imperdiet, feugiat elit. Maecenas ut fermentum metus, a lacinia lacus. Aenean convallis nisi risus, non luctus felis auctor vitae. Morbi ut ex ligula.'),
  ('Birds', '2019-01-04T00:00:00.000Z', 2,
  'Aliquam faucibus elit eu enim convallis, non condimentum ipsum rhoncus. Nullam iaculis, libero at sollicitudin placerat, est nisi luctus est, sit amet ultrices nisl purus non arcu. Nunc tincidunt cursus turpis fringilla dapibus. Sed vestibulum placerat dolor id tempus. Praesent odio massa, congue nec condimentum sed, elementum et ipsum. Proin sed elit in odio suscipit porta laoreet eu ipsum. Vivamus ut suscipit enim. Cras ac ullamcorper mi. In massa urna, viverra ac augue id, sollicitudin rutrum urna. Fusce nec massa sapien. Fusce pharetra quam ante, at accumsan risus suscipit et.'),
  ('Bears', '2018-05-16T23:00:00.000Z', 1,
  'Donec eros dolor, facilisis quis mollis et, molestie ut velit. Etiam mattis diam quis sapien tristique pellentesque. Morbi venenatis enim eget tortor maximus, eget ultrices mauris consectetur. Nulla quis arcu facilisis, dapibus purus at, vulputate nunc. Pellentesque a dolor laoreet, pulvinar elit eu, tristique nibh. Etiam malesuada lectus malesuada, ultricies lectus non, efficitur metus. Cras consequat interdum magna at rutrum. Pellentesque commodo efficitur dui non vulputate. Nam non augue volutpat, pharetra ipsum non, cursus leo. Cras facilisis, orci in placerat semper, est sem iaculis felis, et gravida ipsum erat lobortis purus. Nulla facilisi.'),
  ('Beets', '2018-04-11T23:00:00.000Z', 1,
  'Nulla semper vel lacus sed porta. Vestibulum auctor fringilla justo, non dapibus nunc aliquam vitae. Pellentesque quis odio ut justo aliquet interdum ut vitae risus. Pellentesque vitae tellus dictum, scelerisque neque nec, tristique ipsum. Nulla dictum nisi at maximus tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla eget venenatis urna. Duis leo est, mattis sed libero et, maximus tristique neque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut volutpat neque at volutpat commodo. Mauris consectetur dolor elit, mattis interdum velit cursus sed. Curabitur pulvinar facilisis sollicitudin. Donec purus felis, porta sed ex id, sollicitudin commodo nibh. Curabitur rutrum gravida nunc, id ornare nisl auctor efficitur. Nunc vitae eros a eros facilisis luctus.'),
  ('Battlestar Galactica', '2018-04-26T23:00:00.000Z', 1,
  'Integer accumsan eget felis quis hendrerit. Aenean consectetur, neque sit amet porttitor ultrices, metus leo finibus tellus, at aliquam augue eros a sapien. Suspendisse in metus ac erat pretium aliquam. Suspendisse potenti. Vestibulum consectetur fringilla turpis nec dignissim. Praesent sit amet eros vel erat fringilla eleifend. Proin magna est, pellentesque et ex sed, sodales blandit metus. Sed mattis ipsum eget ante rutrum, rhoncus accumsan metus lacinia. Ut lorem dui, faucibus eget dignissim id, finibus ac ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam porttitor velit ac ipsum aliquet euismod. Phasellus semper tortor quis arcu posuere, ac malesuada leo tristique. Donec nec porttitor elit. Phasellus porta neque nec vestibulum fermentum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget odio dictum, tristique mi sit amet, ornare est.');
    